name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: doc-sum-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Set file permissions
      run: |
        chmod -R 755 .
        chmod +x build_script.sh
        chmod +x startup.sh
        ls -la

    - name: Verify files before deployment
      run: |
        echo "=== Directory Structure ==="
        find . -type f -not -path "*/\.*" -not -path "*/node_modules/*" -not -path "*/env/*"
        
        echo "=== Content of key files ==="
        echo "build_script.sh:"
        cat build_script.sh
        echo "startup.sh:"
        cat startup.sh
        echo ".deployment:"
        cat .deployment

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Post Deployment Info
      if: always()
      run: |
        echo "Deployment finished. Check the app at https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "Check logs in Azure Portal -> Your App -> App Service logs"