name: Deploy to Azure

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'doc-sum-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Configure startup command
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set \
            --resource-group doc-sum-rg \
            --name doc-sum-app \
            --startup-command "./build_script.sh" 