name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # or your default branch
  workflow_dispatch:  # Allows manual triggering

env:
  AZURE_WEBAPP_NAME: doc-sum-app    # Replace with your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Set this to the path to your web app project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # or your Python version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or your Node.js version
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Make scripts executable
      run: |
        chmod +x build_script.sh
        chmod +x startup.sh

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}